apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-testing
  namespace: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 30044
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: redis-cluster
